"""
This type stub file was generated by pyright.
"""

from scapy.arch.libpcap import *
from scapy.arch.unix import *

"""
Customization for the Solaris operation system.
"""
SIOCGIFHWADDR = ...
def get_working_if(): # -> str:
    """Return an interface that works"""
    ...

