"""
This type stub file was generated by pyright.
"""

import scapy.modules.six as six
from scapy.base_classes import Packet_metaclass
from scapy.packet import Packet

"""
ASN.1 Packet

Packet holding data in Abstract Syntax Notation (ASN.1).
"""
class ASN1Packet_metaclass(Packet_metaclass):
    def __new__(cls, name, bases, dct):
        ...
    


class ASN1_Packet(six.with_metaclass(ASN1Packet_metaclass, Packet)):
    ASN1_root = ...
    ASN1_codec = ...
    def self_build(self):
        ...
    
    def do_dissect(self, x):
        ...
    


