"""
This type stub file was generated by pyright.
"""

import socket
from scapy.compat import AddressFamily, Union

"""
Convert IPv6 addresses between textual representation and binary.

These functions are missing when python is compiled
without IPv6 support, on Windows for instance.
"""
_IP6_ZEROS = ...
_INET6_PTON_EXC = socket.error("illegal IP address string passed to inet_pton")
_INET_PTON = ...
def inet_pton(af: AddressFamily, addr: Union[bytes, str]) -> bytes:
    """Convert an IP address from text representation into binary form."""
    ...

_INET_NTOP = ...
def inet_ntop(af: AddressFamily, addr: bytes) -> str:
    """Convert an IP address from binary form into text representation."""
    ...

